### ISSUE TITLE
Flashing on a C-U0007 Nordic chip Unifying receiver

### ISSUE THREAD

**Issue by denwi** [ranma/nrf24lu1-dfu-bootloader#2]
Hello there,

I've recently got a hold of a few of these Logitech dongles with the unsigned bootloader, and I'm looking to flash the SteamVR watchman dongle firmware.

However, I quickly learned that simply using uniflash or the tools in nrf-research-firmware and using my firmware bin file instead does not work. I managed to get my dongle to a working state again thanks to a comment you made in an issue in the aforementioned repo by shorting P0.4 and P0.5 to force it back into the Logitech bootloader.

My question now is, is it possible to flash this first (and without the use of a hardware flasher via SPI for example), then my own firmware file through dfu-util? Or do I need a hardware flasher anyways as I'm under the impression the Logitech bootloader is write-protected. Please correct me if I'm wrong.

Upon a quick inspection, I can confirm that the watchman dongle firmware does start with a LJMP instruction as stated as a requirement by you, so I'm hoping I can use the two together.

Thank you for your time in advance.

**Comment by ranma** [comment]
The logitech bootloader area is write-protected and can only be overwritten using a hardware flasher via SPI.
If the watchman dongle firmware needs to put code into that area it won't work.
Assuming that it doesn't, it could work. Though IIRC there were some bugs still left in the logitech-variant of my bootloader here (ISTR it doesn't always update the checksum correctly).

**Comment by denwi** [comment]
Unfortunately, it's exactly as you say. The watchman dongle firmware seems to require access to 0x7400-0x7800 as data space. (unlike the Logitech firmware that uses 0x6800 to 0x7400 for unifying pairing data, then the Logitech bootloader begins at 0x7400-0x7fff)

I'm not sure if there are easy ways to patch the watchman firmware to use space that doesn't overlap with the write-locked logitech bootloader...
